spring:
  application:
    name: hrpayroll

  datasource:
    url: jdbc:postgresql://localhost:5432/hrpayroll
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO

app:
  cors:
    allowed-origins:
      - http://localhost:5173

